version: '1.0.1'
services: 
  app:
    build: .
    ports: 
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DB_HOST= postgres
      - DB_PORT=5432
      - DB_USER=your_database_user
      - DB_PASSWORD=your_database_password
      - DB_NAME=your_database_name
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER= postgres 
      - POSTGRES_PASSWORD= postgres
      - POSTGRES_DB= star_wars_winrate
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 